---
- name: Install Apache Web Server
  hosts:  webservers
  remote_user: ubuntu
  tasks: 
  - name: Ensure apache2 package is latest 
    apt: 
      name: apache2* 
      state: absent
    notify: Start and enabled apache2 service
    become: True 

  handlers:
   - name: Start and enabled apache2 service
     service: 
      name: apache2 
      state: stopped 
      enabled: True
     become: True
